export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const SET_FETCHED_USER = "SET_FETCHED_USER";


export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";

export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";


